version: '3.5'

services:
  ####################### Nginx #######################
  nginx:
    image: tno:nginx
    restart: on-failure:1
    container_name: tno-nginx
    build:
      context: ./network/nginx
    env_file:
      - network/nginx/.env
    ports:
      - ${NGINX_HTTP_PORT:-50080}:80
      - ${NGINX_HTTPS_PORT:-50443}:443
    networks:
      - tno

  ####################### Keycloak #######################
  keycloak:
    image: tno:keycloak
    restart: on-failure:1
    container_name: tno-keycloak
    build:
      context: ./auth/keycloak
    env_file:
      - auth/keycloak/.env
    volumes:
      - ./auth/keycloak/config/realm-export.json:/tmp/realm-export.json
    ports:
      - ${KEYCLOAK_HTTP_PORT:-50000}:8080
      - ${KEYCLOAK_HTTPS_PORT:-50001}:443
    networks:
      - tno

  ####################### Database #######################
  database:
    image: tno:database
    restart: on-failure:1
    container_name: tno-database
    build:
      context: db/postgres
    env_file:
      - db/postgres/.env
    ports:
      - ${DATABASE_PORT:-50002}:5432
    volumes:
      - tno-database-data:/var/lib/postgressql/data
      - ./db/postgres/scripts:/docker-entrypoint-initdb.d
    networks:
      - tno

  ####################### API - Editor #######################
  api-editor:
    image: tno:api-editor
    restart: on-failure:1
    container_name: tno-api-editor
    build:
      context: api/editor
    env_file: api/editor/.env
    ports:
      - ${API_EDITOR_HTTP_PORT:-50003}:8080
      - ${API_EDITOR_HTTPS_PORT:-50004}:443
    depends_on:
      - database
      - keycloak
    networks:
      - tno

  ####################### App - Editor #######################
  app-editor:
    image: tno:app-editor
    stdin_open: true
    tty: true
    restart: on-failure:1
    container_name: tno-app-editor
    build:
      context: app/editor
    env_file: ./app/editor/.env
    volumes:
      - ./app/editor/src:/usr/app/src
      - ./app/editor/public:/usr/app/public
      - tno-app-editor-node-cache:/usr/app/node_modules
    ports:
      - ${APP_EDITOR_HTTP_PORT:-50005}:3000
      - ${APP_EDITOR_HTTPS_PORT:-50006}:3443
    depends_on:
      - api-editor
    networks:
      - tno

####################### Networks Definition #######################
networks:
  tno:
    name: tno-net
    driver: bridge

####################### Volumes Definition #######################
volumes:
  tno-database-data:
    name: tno-database-data
  tno-app-editor-node-cache:
    name: tno-app-editor-node-cache
