---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - pvc.yaml
  - config-map.yaml
  - deploy.yaml
  - service.yaml

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: ssh-key
    type: file
    env: id_rsa