---
version: '3.5'

services:
  zookeeper:
    image: tno:kafka-zookeeper
    restart: on-failure:1
    hostname: zookeeper
    container_name: tno-zookeeper
    build:
      context: db/kafka/zookeeper
    env_file:
      - db/kafka/zookeeper/.env
    ports:
      - ${KAFKA_ZOOKEEPER_PORT:-50010}:2181
    volumes:
      - tno-zookeeper-data:/var/lib/zookeeper/data
      - tno-zookeeper-log:/var/lib/zookeeper/log
    networks:
      - tno

  broker:
    image: tno:kafka-broker
    restart: on-failure:1
    hostname: broker
    container_name: tno-broker
    build:
      context: db/kafka/broker
    env_file:
      - db/kafka/broker/.env
    depends_on:
      - zookeeper
    ports:
      # - ${KAFKA_BROKER_PORT:-50011}:9101
      - ${KAFKA_BROKER_ADVERTISED_HOST_PORT:-50012}:9092
      - ${KAFKA_BROKER_ADVERTISED_EXTERNAL_PORT:-50019}:29094
      # - ${KAFKA_BROKER_REST_PORT:-50017}:8090
    volumes:
      - tno-broker-data:/var/lib/kafka/data
    networks:
      - tno

  rest-proxy:
    image: tno:kafka-rest-proxy
    restart: on-failure:1
    hostname: rest-proxy
    container_name: tno-rest-proxy
    build:
      context: db/kafka/rest-proxy
    env_file:
      - db/kafka/rest-proxy/.env
    depends_on:
      - broker
    ports:
      - ${KAFKA_REST_PROXY_PORT:-50018}:8082
    networks:
      - tno

  cat:
    image: tno:kafkacat
    restart: on-failure:1
    hostname: cat
    container_name: tno-kafkacat
    build:
      context: db/kafka/cat
    depends_on:
      - broker
    networks:
      - tno

####################### Volumes Definition #######################
volumes:
  tno-zookeeper-data:
    name: tno-zookeeper-data
  tno-zookeeper-log:
    name: tno-zookeeper-log
  tno-broker-data:
    name: tno-broker-data
