debug: false

logging:
  level:
    org:
      springframework:
        context: DEBUG

spring:
  main:
    banner-mode: 'off'

  h2:
    console:
      enabled: false
      
  datasource:
    url: ${env.DB_URL:jdbc:postgresql://database:5432/tno}
    username: ${env.DB_USERNAME}
    password: ${env.DB_PASSWORD}

  flyway:
    enabled: ${env.DB_MIGRATION_ENABLED:false}
    validate-on-migrate: ${env.DB_VALIDATE_MIGRATION:true}

  jpa:
    show-sql: ${env.JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
    hibernate:
      ddl-auto: ${env.JPA_DDL_AUTO:none}
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
